config/routes.rb
Bap::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :games 

  resources :categories do
    get 'games_by_category'
  end

  get 'contact' => 'games#contact'
  get 'theory' => 'games#theory'

  root 'games#theory'

  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :games
end

app/models/game.rb
class Game < ActiveRecord::Base
  validates :category_id, presence: true
  validates :name, presence: true
  validates :desc, presence: true
  belongs_to :category

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  def games_by_category
    @games = Game.where(:category_id => params[:category_id])
    @category = Category.find(params[:category_id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :desc)
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)
    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render action: 'show', status: :created, location: @game }
      else
        format.html { render action: 'new' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end

  def contact

  end

  def theory

  end  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :desc, :materials, :participants, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/games_by_category.html.erb
<h1><%= @category.name %></h1>
<% j = 0 %>
<% @games.each do |game| %>
  <% j = j + 1 %>
  <% if j ==1%>
    <div class="row">
  <% end%>
  <div class="large-4 columns">
    <ul class="pricing-table">
      <li class="price"><%=game.name%></li>
      <li class="description"><%=game.desc%></li>
      <li class="bullet-item">CAT: <%=game.category.name%></li>
      <li class="bullet-item">PX: <%=game.participants%></li>
      <li class="bullet-item">MAT: <%=game.materials%></li>
      <li class="cta-button">
        <%= link_to 'Detalle', game %>
      </li>
    </ul>
  </div>
  <% if j == 3 or j >= @games.count%>
    <% j = 0 %>
    </div>
  <% end%>
<% end %>

app/views/categories/index.html.erb
<h1>Categorías de Juegos</h1>
<% j = 0 %>
<% @categories.each do |category| %>
  <% j = j + 1%>
  <% if j == 1%>
    <div class="row">
  <% end%>
  <div class="large-4 columns">
    <ul class="pricing-table">
      <li class="price"><%=category.name%></li>
      <li class="description"><%=category.desc%></li>
      <li class="bullet-item"># de Juegos: <%= link_to category.games.count, category_games_by_category_path(category.id), title: "Ver los juegos de esta categoría" %></li>
    </ul>
  </div>
  <% if j == 3 or j >=@categories.count %>
    <% j = 0 %>
    </div>
  <% end%>

<% end %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @category.desc %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="field">
    <%= f.label :materials %><br>
    <%= f.text_field :materials %>
  </div>
  <div class="field">
    <%= f.label :participants %><br>
    <%= f.text_field :participants %>
  </div>
  <div class="field">
    <%= f.label :categoy %><br>
    <%= collection_select(:game, :category_id, Category.all, :id, :name, prompt: true)%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/contact.html.erb
<div class="row">
  <div class ="large-6 columns">
    <h3> Sobre B.A.P. </h3>
    <p>
    Esta B.A.P. (Bolsa de Actividades Portátiles) ha sido recompilado por varias personas de <a href="www.recojo.net" title="Visita RECOJO">RECOJO</a> Red Colombiana de Jóvenes y está aquí para que le hagas uso cuando tengas que manejar grupos de personas y quieras hacer actividades sin muchos materiales y con gran impacto.
    </p>
    <p>
      Si tienes alguna duda, porfavor envíanos un <a href="mailto:contactanos@recojo.net,carloslopez@recojo.net" title="Envía un correo a contactanos@recojo.net">mail</a> con tus comentarios.
    </p>
    <div class="row">
      <div class="small-3 small-centered columns">
        <a href="http://www.recojo.net" title="Visita RECOJO"><img src="http://www.recojo.net/uploads/1/8/1/7/181752/6784599.jpg"/></a>
      </div>
    </div>
  </div>
  <div class ="large-6 columns">
    <h3> Bibliografía recomendada </h3>
    <p>
      A continuación listamos una serie de libros y sitios en los que se pueden encontrar muchas más actividades.
    </p>
    <p>
      <ul>
      <li> <a href="http://www.ultimatecampresource.com"> www.ultimatecampresource.com</a></li>
      <li> <a href="http://www.campgames.org"> www.campgames.org</a></li>
      <li> Manual de Campamento, Asociación Venezolana de Campamentos.</li>
      <li>Quicksilver, Karl Rohnke y Steve Butler.</li>
      <li> Cooperative Sports and Game Book, Terry Orlick</li>
      <li> Fun and Games, Camp Tawingo </li>
      <li>Fun Stuff, Karl Rohnke</li>
      </ul>
    </p>
  </div>
</div>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Todos los Juegos</h1>
<% j = 0 %>
<% @games.each do |game| %>
  <% j = j + 1 %>
  <% if j == 1%>
    <div class="row">
  <% end%>
  <div class="large-4 columns">
    <ul class="pricing-table">
      <li class="price"><%=game.name%></li>
      <li class="description"><%=game.desc%></li>
      <li class="bullet-item">CAT: <%= link_to game.category.name, category_games_by_category_path(game.category.id)%></li>
      <li class="bullet-item">PX: <%=game.participants%></li>
      <li class="bullet-item">MAT: <%=game.materials%></li>
      <li class="cta-button">
        <%= link_to 'Detalle', game %>
      </li>
    </ul>
  </div>
  <% if j == 3 or j >= @games.count%>
    <% j = 0 %>
    </div>
  <% end%>
<% end %>

app/views/games/index_old.html.erb
<h1>Todos los Juegos</h1>



<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripción</th>
      <th>Materiales</th>
      <th>Participantes</th>
      <th>Categoría</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.name %></td>
        <td><%= game.desc %></td>
        <td><%= game.materials %></td>
        <td><%= game.participants %></td>
        <td><%= game.category.name %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path, class: "button radius" %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @game.name %>
</p>

<p>
  <strong>Descripción:</strong>
  <%= @game.desc %>
</p>

<p>
  <strong>Materiales:</strong>
  <%= @game.materials %>
</p>

<p>
  <strong>Participantes:</strong>
  <%= @game.participants %>
</p>

<p>
  <strong>Categoría:</strong>
  <%= @game.category.name %>
</p>

<%= link_to 'Ver todos los juegos', games_path , :class => "button radius"%>

app/views/games/theory.html.erb
<div class="row">
  <div class="large-12 columns">
      <h2> Bienvenido al B.A.P. </h2>
      <h3> Introducción </h3>
      <h4>¿Alguna vez has tenido que diseñar actividades para grupos de trabajo? </h4>
      <p>
El manual B.A.P (Bolsa de Actividades portátiles) contiene actividades para todo tipo de grupos, edades y ambientes, en él encontraras una compilación de actividades de una gran variedad de libros y de la experiencia de nuestros facilitadores, que te harán el proceso de diseño de actividades mucho más fácil.
</p>
<p>
Para empezar a planear una secuencia de actividades, debes asegúrate de tener la respuesta a estas preguntas:
</p>
<ul>
<li>¿Cuál es el objetivo de la secuencia?</li>
<li>¿Cuántos participantes van a asistir?</li>
<li> ¿Qué edades tienen?</li>
<li> ¿Se conocen entre ellos?</li>
<li> ¿Alguno tiene lesiones o restricciones de movimiento?</li>
<li>¿Con qué espacios cuentas para hacer las actividades?</li>
<li>¿Con cuánto tiempo dispones?</li>
</ul>
<p>
Esto te ayudará a seleccionar las actividades más idóneas para lograr el objetivo que te propones.
</p>
<p>
Una secuencia debe empezar  con un rompehielos, un calentamiento, un reto o actividad central y un cierre o retroalimentación (si quieres dejar un aprendizaje).
</p>
<p>
Asegúrate de llenar la siguiente tabla para todas las secuencias que planees.
</p>

      <div class="row">
        <div class="large-2 columns panel">
          Tiempo:
        </div>
        <div class="large-2 columns panel">
          Actividad:
        </div>
        <div class="large-2 columns panel">
          Objetivo y Reglas:
        </div>
        <div class="large-2 columns panel">
          Preguntas o Comentarios:
        </div>
        <div class="large-2 columns panel">
          Encargad@s:
        </div>
        <div class="large-2 columns panel">
          Materiales:
        </div>
      </div>
  </div>
</div>
<div class="row">
  <div class="large-12 columns">
    <h2>Ciclo de la Educación Experiencial</h2>
    <img src="https://s3.amazonaws.com/recojo/BAP+Ciclo+Ed+Exp.png"/>
  </div>
</div>
<div class="row">
  <div class="large-12 columns">
    <h2>Reto por Opción</h2>
    <img src="https://s3.amazonaws.com/recojo/BAP+rxo.png"/>
  </div>
</div>
<div class="row">
  <div class="large-12 columns">
    <h2>DDADAC</h2>
    <h4> GUÍA PARA PRESENTAR ACTIVIDADES </h4>
    <h5>Describe</h5>
    <p>
Presenta el objetivo y las reglas de la actividad de la manera más sencilla posible. Habla claro para que todos puedan oírte. Usa la fantasía y el humor adecuadamente.
Se creativo en tu presentación pero ten cuidado de no confundir a la gente con muchos detalles.
</p>
<h5>Demonstrate -  Demuestra</h5>
<p>
Refuerza tu explicación con ejemplos visuales y motores-
</p>
<h5>Ask – Pregunta</h5>
<p>
Antes de empezar la actividad asegúrate de saber si algún participante necesita aclaración.
Si hay muchas preguntas usa tu juicio para saber si en verdad necesitan aclaración o no. Muchas preguntas pueden interrumpir el flujo que quieres crear con el grupo, hay que estar atento.
</p>
<h5>Do – Juega, Haz</h5>
<p>
Muchas veces es mejor empezar la actividad para que la entiendan durante la práctica.
Si esperas a que todos entiendan las reglas desde el comienzo nunca va a empezar la actividad. Algo de confusión hace parte del juego.
</p>
<h5>Adapt - Adapta</h5>
<p>
Asegúrate de que los participantes estén metidos en la actividad. Si lo están déjala fluir; si te das cuenta que la energía está bajando, cambia las reglas, de inicio a un nivel más, más complejo, o cambia de actividad (esto es clave trabajando con niños)
</p>
<h5>Close -  Cierra</h5>
<p>
Siempre ten en cuenta que hay que cerrar las actividades, sobretodo si éstas involucran conteos, puntajes o ganador
</p>

  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "B.A.P. (Bolsa de Actividades Portátiles) por RECOJO" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

<nav class="top-bar hide-for-small">
  <ul class="title-area">
    <!-- Title Area -->
    <li class="name">
      <h1><a href="/">B.A.P. </a></h1>
    </li>
    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>
  <section class="top-bar-section">
    <ul class="right">
      <li class="divider"></li>
      <li><%= link_to "Teoría", '/theory' %></li>            
      <li class="divider"></li>
      <li><%= link_to "Juegos", games_path %></li>
      <li class="divider"></li>
      <li><%= link_to "Categorías", categories_path %></li>
      <li class="divider"></li>
      <li><%= link_to "Contacto" , '/contact'%></li>
    </ul>
  </section>
</nav>
<div class="row hide-for-medium-up">
      <div class="small-4 columns">
        <%= link_to "Teoría", '/theory', class: "button radius"  %>
      </div>
      <div class="small-4 columns">
        <%= link_to "Juegos", games_path , class: "button radius"%>
      </div>
      <div class="small-4 columns">
        <%= link_to "Categorías", categories_path, class: "button radius" %>
      </div>
      <div class="small-3 columns hide-for-small">
        <%= link_to "Contacto" , '/contact', class: "button radius"%>
      </div>
</div>
<div class="row">
  <div class="large-12 columns"><%= yield %></div>
</div>
<div class="row">
  <div class="large-12 columns">
    <div style="margin-top:100px;">
     Si tienes preguntas, o comentarios <a href="/contact">contáctanos</a>
   </div>
  </div>
</div>

    
    <%= javascript_include_tag "application" %>
  </body>
</html>